In [3]:
import pandas as pd
# create Dataframe from RewardsData CSV
rewards_df = pd.read_csv("RewardsData.csv")

# view first 20 records
rewards_df.head(20)

,User ID,Birthdate,City,State,Zip,Available Points,Total Points Earned,Points Spent,Joined On,Last Seen,Tags
0,1,1/31/1992,Minneapolis,Georgia,55401,300,300,0,9/4/2020 0:15,12/16/2021 17:42,ClassOf2025
1,2,NaN,Los Angeles,Colorado,90210,320,320,0,8/19/2020 11:15,4/13/2022 14:28,ClassOf2025|apple
2,3,1/11/1990,Merida,AL,97204,330,330,0,10/13/2020 16:20,4/21/2021 10:54,Freshman|Developer
3,4,4/16/1990,Winston-Salem,NC,27106,10790,14290,3500,8/18/2020 13:21,6/30/2022 22:22,GraduateStudent|admin|MBBvsDuke
4,5,3/24/1994,Winston-Salem,NC,27109,650,650,0,8/21/2020 11:27,12/30/2020 10:57,Student|NOBSBvsNDGame3|NOBSBvsNDGame3A
5,6,10/9/1995,G,AL,85588,7085,7395,310,8/18/2020 14:28,6/8/2022 23:55,GraduateStudent|admin
6,7,9/22/1995,NaN,NaN,NaN,570,570,0,8/21/2020 10:23,4/27/2022 16:27,ClassOf2025
7,8,NaN,NaN,NaN,NaN,2410,2410,0,8/22/2020 13:53,3/31/2022 1:56,ClassOf2022|21DZ
8,9,NaN,NaN,NaN,NaN,2895,3195,300,8/22/2020 14:03,10/10/2021 16:05,Student|Senior|DriveInNCSU|ClassificationPts|1...
9,10,7/20/1999,Winston Salem,NC,27106,8465,8515,50,8/22/2020 14:42,4/9/2022 14:10,GraduateStudent
10,11,7/22/2000,NaN,NaN,NaN,22210,22210,0,8/22/2020 15:59,6/21/2022 19:32,ClassOf2022
11,12,NaN,NaN,NaN,NaN,1355,4355,3000,8/22/2020 17:37,5/18/2021 20:57,Student|Senior|DriveInNCSU|ClassificationPts|1...
12,13,NaN,NaN,NaN,NaN,3290,3290,0,8/22/2020 18:20,4/10/2022 23:04,Student|Senior|ClassificationPts|CampbellGroup...
13,14,11/1/2000,Winston-Salem,NC,27106,10965,17165,6200,8/22/2020 20:02,5/11/2022 15:16,ClassOf2023|MBBvsDuke
14,15,6/27/2000,Thomasville,NC,27360,5750,5750,0,8/23/2020 9:26,4/11/2022 16:27,ClassOf2022
15,16,4/24/1999,NaN,NaN,NaN,4310,4610,300,8/23/2020 23:43,8/27/2021 13:01,Student|Senior|ClassificationPts|BSBvNDGame1|B...
16,17,NaN,NaN,NaN,NaN,890,890,0,8/24/2020 11:30,1/23/2022 23:28,ClassOf2022
17,18,7/5/1998,NaN,NaN,NaN,550,550,0,8/24/2020 14:48,10/26/2020 10:01,NOBSBvsNDGame3|NOBSBvsNDGame3A
18,19,NaN,Goldsboro,North Carolina,27534,3425,3425,0,8/24/2020 15:35,6/30/2022 21:19,ClassOf2023|21EPI|MBBvsDuke
19,20,NaN,NaN,NaN,NaN,800,800,0,8/24/2020 18:23,NaN,Student|19RetroactivePoints|NOBSBvsNDGame3|NOB...

The Pandas .isna() function is used to identify and return Boolean values (True or False) for each element in a DataFrame or Series, indicating
whether the element is missing or contains a NaN (Not-a-Number) value. True if value is missing and False if the value is present.

In [5]:
rewards_df.isna()

,User ID,Birthdate,City,State,Zip,Available Points,Total Points Earned,Points Spent,Joined On,Last Seen,Tags
0,False,False,False,False,False,False,False,False,False,False,False
1,False,True,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
7247,False,True,True,True,True,False,False,False,False,False,False
7248,False,True,True,True,True,False,False,False,False,False,False
7249,False,False,True,True,True,False,False,False,False,False,False
7250,False,True,True,True,True,False,False,False,False,False,False
7251,False,True,True,True,True,False,False,False,False,False,False

In [8]:
# we can then use the .sum() function to get a count of the total number of missing values
missing_value_counts = rewards_df.isna().sum()
missing_value_counts

User ID                   0
Birthdate              6080
City                   6922
State                  6922
Zip                    6922
Available Points          0
Total Points Earned       0
Points Spent              0
Joined On                 0
Last Seen               221
Tags                      0
dtype: int64

In [10]:
# create and display missing value percentage variable
missing_value_percentages = missing_value_counts / len(rewards_df) * 100
missing_value_percentages

User ID                 0.000000
Birthdate              83.838941
City                   95.449531
State                  95.449531
Zip                    95.449531
Available Points        0.000000
Total Points Earned     0.000000
Points Spent            0.000000
Joined On               0.000000
Last Seen               3.047435
Tags                    0.000000
dtype: float64

In [11]:
rewards_df['Last Seen']

0       12/16/2021 17:42
1        4/13/2022 14:28
2        4/21/2021 10:54
3        6/30/2022 22:22
4       12/30/2020 10:57
              ...
7247     6/30/2022 12:04
7248     6/28/2022 22:43
7249     6/30/2022 12:48
7250     6/30/2022 20:39
7251       7/1/2022 2:42
Name: Last Seen, Length: 7252, dtype: object

In [12]:
# convert the 'Last Seen' column from a generic object to datetime
rewards_df['Last Seen'] = pd.to_datetime(rewards_df['Last Seen'])

In [13]:
rewards_df['Last Seen']

0      2021-12-16 17:42:00
1      2022-04-13 14:28:00
2      2021-04-21 10:54:00
3      2022-06-30 22:22:00
4      2020-12-30 10:57:00
               ...
7247   2022-06-30 12:04:00
7248   2022-06-28 22:43:00
7249   2022-06-30 12:48:00
7250   2022-06-30 20:39:00
7251   2022-07-01 02:42:00
Name: Last Seen, Length: 7252, dtype: datetime64[ns]

In [14]:
rewards_df['Last Seen'].max()

Timestamp('2022-07-01 08:36:00')

In [15]:
rewards_df['Last Seen'].min()

Timestamp('2020-10-12 14:38:00')

The Pandas .fillna function is used to replace any missing (NaN) values in a DataFrame or Series with specified values

In [16]:
rewards_df['Last Seen'].fillna(value=rewards_df['Last Seen'].min())

0      2021-12-16 17:42:00
1      2022-04-13 14:28:00
2      2021-04-21 10:54:00
3      2022-06-30 22:22:00
4      2020-12-30 10:57:00
               ...
7247   2022-06-30 12:04:00
7248   2022-06-28 22:43:00
7249   2022-06-30 12:48:00
7250   2022-06-30 20:39:00
7251   2022-07-01 02:42:00
Name: Last Seen, Length: 7252, dtype: datetime64[ns]

In [18]:
rewards_df['Last Seen'].fillna(value=rewards_df['Last Seen'].min(), inplace=True)  #inplace avoids creating separate copy

In [20]:
# get a count of total number of missing values
missing_value_counts = rewards_df.isna().sum()
print(missing_value_counts)

User ID                   0
Birthdate              6080
City                   6922
State                  6922
Zip                    6922
Available Points          0
Total Points Earned       0
Points Spent              0
Joined On                 0
Last Seen                 0
Tags                      0
dtype: int64

In [22]:
# drop records with missing values and assign result to new dataframe
rewards_df_sample = rewards_df.dropna()
rewards_df_sample

,User ID,Birthdate,City,State,Zip,Available Points,Total Points Earned,Points Spent,Joined On,Last Seen,Tags
0,1,1/31/1992,Minneapolis,Georgia,55401,300,300,0,9/4/2020 0:15,2021-12-16 17:42:00,ClassOf2025
2,3,1/11/1990,Merida,AL,97204,330,330,0,10/13/2020 16:20,2021-04-21 10:54:00,Freshman|Developer
3,4,4/16/1990,Winston-Salem,NC,27106,10790,14290,3500,8/18/2020 13:21,2022-06-30 22:22:00,GraduateStudent|admin|MBBvsDuke
4,5,3/24/1994,Winston-Salem,NC,27109,650,650,0,8/21/2020 11:27,2020-12-30 10:57:00,Student|NOBSBvsNDGame3|NOBSBvsNDGame3A
5,6,10/9/1995,G,AL,85588,7085,7395,310,8/18/2020 14:28,2022-06-08 23:55:00,GraduateStudent|admin
...,...,...,...,...,...,...,...,...,...,...,...
7228,7219,6/12/2004,Lutherville,Maryland,21093,490,490,0,6/22/2022 17:28,2022-06-30 08:43:00,Student|ClassOf2026
7229,7220,8/7/1999,Winston-Salem,North Carolina,27106,430,430,0,6/22/2022 17:36,2022-06-26 16:39:00,Student|ClassOf2023
7236,7227,3/14/2000,Clemmons,North Carolina,27012,460,460,0,6/23/2022 22:18,2022-06-29 23:40:00,Student|GraduateStudent
7239,7230,5/18/1999,Winston Salem,North Carolina,27107,410,410,0,6/24/2022 16:03,2022-06-24 16:06:00,Student|GraduateStudent
7244,7235,6/20/2004,Guaynabo,Puerto Rico,969,440,440,0,6/27/2022 10:21,2022-07-01 08:36:00,Student|ClassOf2026

In [23]:
# get a count of tatal number of missing values
missing_value_counts = rewards_df_sample.isna().sum()
print(missing_value_counts)

User ID                0
Birthdate              0
City                   0
State                  0
Zip                    0
Available Points       0
Total Points Earned    0
Points Spent           0
Joined On              0
Last Seen              0
Tags                   0
dtype: int64

In [24]:
# drop the 'Tags' column from rewards_df_sample
rewards_df_sample = rewards_df_sample.drop(columns='Tags')
rewards_df_sample

,User ID,Birthdate,City,State,Zip,Available Points,Total Points Earned,Points Spent,Joined On,Last Seen
0,1,1/31/1992,Minneapolis,Georgia,55401,300,300,0,9/4/2020 0:15,2021-12-16 17:42:00
2,3,1/11/1990,Merida,AL,97204,330,330,0,10/13/2020 16:20,2021-04-21 10:54:00
3,4,4/16/1990,Winston-Salem,NC,27106,10790,14290,3500,8/18/2020 13:21,2022-06-30 22:22:00
4,5,3/24/1994,Winston-Salem,NC,27109,650,650,0,8/21/2020 11:27,2020-12-30 10:57:00
5,6,10/9/1995,G,AL,85588,7085,7395,310,8/18/2020 14:28,2022-06-08 23:55:00
...,...,...,...,...,...,...,...,...,...,...
7228,7219,6/12/2004,Lutherville,Maryland,21093,490,490,0,6/22/2022 17:28,2022-06-30 08:43:00
7229,7220,8/7/1999,Winston-Salem,North Carolina,27106,430,430,0,6/22/2022 17:36,2022-06-26 16:39:00
7236,7227,3/14/2000,Clemmons,North Carolina,27012,460,460,0,6/23/2022 22:18,2022-06-29 23:40:00
7239,7230,5/18/1999,Winston Salem,North Carolina,27107,410,410,0,6/24/2022 16:03,2022-06-24 16:06:00
7244,7235,6/20/2004,Guaynabo,Puerto Rico,969,440,440,0,6/27/2022 10:21,2022-07-01 08:36:00

In [28]:
# get list of unique values for city column
city_unique_values = rewards_df_sample['City'].unique()
# sort values
city_unique_values.sort()
city_unique_values

array(['Atlanta', 'Aurora ', 'Austin', 'Bakersfield', 'Belmont ',
       'Bethesda ', 'Bourne', 'Chapel Hill', 'Charlotte', 'Charlotte ',
       'Clemmons', 'Cleveland', 'Clovis', 'Dallas', 'Delhi', 'Delran',
       'Downers Grove', 'Durham', 'Duxbury', 'Edina', 'Fort Myers ', 'G',
       'Gainesville', 'Greensboro', 'Guaynabo', 'Huntersville',
       'Indian Trail', 'Jacksonville ', 'Jamesville', 'Larchmont',
       'Libertyville', 'Lincoln University', 'Littleton', 'Lmao',
       'Locust', 'Louisville', 'Lutherville', 'Malvern',
       'Manhattan beach ', 'Marblehead', 'Memphis', 'Merida', 'Milwaukee',
       'Minneapolis ', 'Mooresville', 'Morganton', 'Mt. Pleasant ',
       'Nashville', 'Northport', 'Oakwood', 'Orleans ', 'Ormond Beach',
       'Palm Beach Gardens', 'Palmetto Bay', 'Perry', 'Pittsburgh', 'Rex',
       'Rocky hill', 'Rome', 'San Marcos', 'Sharon', 'Smithtown',
       'Summit', 'Supply', 'Terrace Park', 'Thomasville', 'Valrico ',
       'Walkertown', 'Waukegan', 'Waxhaw', 'West Chester', 'Weston',
       'Westport', 'Whitesboro', 'Winston Salem', 'Winston Salem ',
       'Winston salem', 'Winston salem ', 'Winston-Salem',
       'Winston-Salem ', 'Winston-Salem, NC', 'Winston-salem', 'Wyckoff',
       'dover', 'winston salem '], dtype=object)

In [30]:
# replace variations of Winston-Salem with the correct format
rewards_df_sample['City'].replace(to_replace=['Winston Salem', 'Winston Salem ',
       'Winston salem', 'Winston salem ', 'Winston-Salem',
       'Winston-Salem ', 'Winston-Salem, NC', 'Winston-salem'], value = "Winston-Salem", inplace=True)

In [34]:
# remove all leading and trailing spaces from city column
rewards_df_sample['City'] = rewards_df_sample['City'].str.strip()

The str keyword is used here as a way to access methods that oeprate on string objects directly from the class itself, without having to 
create a string instance

In [37]:
# fix any casing issues present in City List
rewards_df_sample['City'] = rewards_df_sample['City'].str.title()

In [39]:
# get list of unique values for city column
city_unique_values = rewards_df_sample['City'].unique()
# sort values
city_unique_values.sort()
city_unique_values

array(['Atlanta', 'Aurora', 'Austin', 'Bakersfield', 'Belmont',
       'Bethesda', 'Bourne', 'Chapel Hill', 'Charlotte', 'Clemmons',
       'Cleveland', 'Clovis', 'Dallas', 'Delhi', 'Delran', 'Dover',
       'Downers Grove', 'Durham', 'Duxbury', 'Edina', 'Fort Myers', 'G',
       'Gainesville', 'Greensboro', 'Guaynabo', 'Huntersville',
       'Indian Trail', 'Jacksonville', 'Jamesville', 'Larchmont',
       'Libertyville', 'Lincoln University', 'Littleton', 'Lmao',
       'Locust', 'Louisville', 'Lutherville', 'Malvern',
       'Manhattan Beach', 'Marblehead', 'Memphis', 'Merida', 'Milwaukee',
       'Minneapolis', 'Mooresville', 'Morganton', 'Mt. Pleasant',
       'Nashville', 'Northport', 'Oakwood', 'Orleans', 'Ormond Beach',
       'Palm Beach Gardens', 'Palmetto Bay', 'Perry', 'Pittsburgh', 'Rex',
       'Rocky Hill', 'Rome', 'San Marcos', 'Sharon', 'Smithtown',
       'Summit', 'Supply', 'Terrace Park', 'Thomasville', 'Valrico',
       'Walkertown', 'Waukegan', 'Waxhaw', 'West Chester', 'Weston',
       'Westport', 'Whitesboro', 'Winston Salem', 'Winston-Salem',
       'Wyckoff'], dtype=object)

In [41]:
# get list of unique values for city column
state_unique_values = rewards_df_sample['State'].unique()
# sort values
state_unique_values.sort()
state_unique_values

array(['AL', 'CT', 'California', 'Colorado', 'Connecticut',
       'District of Columbia', 'FL', 'Florida', 'GA', 'Georgia',
       'Illinois', 'Kentucky', 'MA', 'MD', 'MN', 'Maryland',
       'Massachusetts', 'NC', 'NJ', 'NY', 'New Jersey', 'New Mexico',
       'New York', 'North Carolina', 'OH', 'Ohio', 'PA', 'Pennsylvania',
       'Puerto Rico', 'SC', 'TN', 'TX', 'Tennessee', 'Texas', 'WI'],
      dtype=object)

The 'State' column is currently a mixture of state names and abbreviations. A quick web search for "python dicitionary of state of abbreviations" provided a complete dictionary of US state names and abbreviations

In [42]:
# Create a dictionary to map full state names to abbreviations
us_state_to_abbrev = {
    "Alabama": "AL", "Alaska": "AK", "Arizona": "AZ", "Arkansas": "AR", "California": "CA",
    "Colorado": "CO", "Connecticut": "CT", "Delaware": "DE", "Florida": "FL", "Georgia": "GA",
    "Hawaii": "HI", "Idaho": "ID", "Illinois": "IL", "Indiana": "IN", "Iowa": "IA",
    "Kansas": "KS", "Kentucky": "KY", "Louisiana": "LA", "Maine": "ME", "Maryland": "MD",
    "Massachusetts": "MA", "Michigan": "MI", "Minnesota": "MN", "Mississippi": "MS", "Missouri": "MO",
    "Montana": "MT", "Nebraska": "NE", "Nevada": "NV", "New Hampshire": "NH", "New Jersey": "NJ",
    "New Mexico": "NM", "New York": "NY", "North Carolina": "NC", "North Dakota": "ND", "Ohio": "OH",
    "Oklahoma": "OK", "Oregon": "OR", "Pennsylvania": "PA", "Rhode Island": "RI", "South Carolina": "SC",
    "South Dakota": "SD", "Tennessee": "TN", "Texas": "TX", "Utah": "UT", "Vermont": "VT",
    "Virginia": "VA", "Washington": "WA", "West Virginia": "WV", "Wisconsin": "WI", "Wyoming": "WY",
    "District of Columbia": "DC", "Puerto Rico": "PR"
}

In [44]:
for state_name in us_state_to_abbrev:
    # Instead of inplace=True, we assign the result back to the column
    rewards_df_sample['State'] = rewards_df_sample['State'].replace(to_replace=state_name, value=us_state_to_abbrev[state_name])

# Verify the changes
print(rewards_df_sample['State'].unique())

['GA' 'AL' 'NC' 'MD' 'FL' 'MA' 'CT' 'NJ' 'WI' 'PA' 'NY' 'TX' 'IL' 'OH'
 'SC' 'CA' 'DC' 'CO' 'MN' 'KY' 'TN' 'NM' 'PR']

In [47]:
# Convert us_state_to_abbrev dictionary to DataFrame for merging
states_df = pd.DataFrame(list(us_state_to_abbrev.items()), columns=['State name', 'State'])
states_df.head(3)

  State name State
0    Alabama    AL
1     Alaska    AK
2    Arizona    AZ

In [50]:
# Merge the original DataFrame with the states DataFrame
rewards_df_sample=pd.merge(rewards_df_sample, states_df, on='State', how='left')
rewards_df_sample

,User ID,Birthdate,City,State,Zip,Available Points,Total Points Earned,Points Spent,Joined On,Last Seen,State name_x,State name_y
0,1,1/31/1992,Minneapolis,GA,55401,300,300,0,9/4/2020 0:15,2021-12-16 17:42:00,Georgia,Georgia
1,3,1/11/1990,Merida,AL,97204,330,330,0,10/13/2020 16:20,2021-04-21 10:54:00,Alabama,Alabama
2,4,4/16/1990,Winston-Salem,NC,27106,10790,14290,3500,8/18/2020 13:21,2022-06-30 22:22:00,North Carolina,North Carolina
3,5,3/24/1994,Winston-Salem,NC,27109,650,650,0,8/21/2020 11:27,2020-12-30 10:57:00,North Carolina,North Carolina
4,6,10/9/1995,G,AL,85588,7085,7395,310,8/18/2020 14:28,2022-06-08 23:55:00,Alabama,Alabama
...,...,...,...,...,...,...,...,...,...,...,...,...
167,7219,6/12/2004,Lutherville,MD,21093,490,490,0,6/22/2022 17:28,2022-06-30 08:43:00,Maryland,Maryland
168,7220,8/7/1999,Winston-Salem,NC,27106,430,430,0,6/22/2022 17:36,2022-06-26 16:39:00,North Carolina,North Carolina
169,7227,3/14/2000,Clemmons,NC,27012,460,460,0,6/23/2022 22:18,2022-06-29 23:40:00,North Carolina,North Carolina
170,7230,5/18/1999,Winston-Salem,NC,27107,410,410,0,6/24/2022 16:03,2022-06-24 16:06:00,North Carolina,North Carolina
171,7235,6/20/2004,Guaynabo,PR,969,440,440,0,6/27/2022 10:21,2022-07-01 08:36:00,Puerto Rico,Puerto Rico

In [51]:
# rename 'State' column to 'State Abbreviation'
rewards_df_sample.rename(columns={'State': 'State Abbreviation'}, inplace=True)
rewards_df_sample.head(3)

,User ID,Birthdate,City,State Abbreviation,Zip,Available Points,Total Points Earned,Points Spent,Joined On,Last Seen,State name_x,State name_y
0,1,1/31/1992,Minneapolis,GA,55401,300,300,0,9/4/2020 0:15,2021-12-16 17:42:00,Georgia,Georgia
1,3,1/11/1990,Merida,AL,97204,330,330,0,10/13/2020 16:20,2021-04-21 10:54:00,Alabama,Alabama
2,4,4/16/1990,Winston-Salem,NC,27106,10790,14290,3500,8/18/2020 13:21,2022-06-30 22:22:00,North Carolina,North Carolina

In [52]:
# 1. Drop the redundant 'State name_x' column
rewards_df_sample.drop(columns=['State name_x'], inplace=True)

# 2. Rename 'State name_y' to just 'State Name'
rewards_df_sample.rename(columns={'State name_y': 'State Name'}, inplace=True)

# 3. View the final clean result
rewards_df_sample.head()

,User ID,Birthdate,City,State Abbreviation,Zip,Available Points,Total Points Earned,Points Spent,Joined On,Last Seen,State Name
0,1,1/31/1992,Minneapolis,GA,55401,300,300,0,9/4/2020 0:15,2021-12-16 17:42:00,Georgia
1,3,1/11/1990,Merida,AL,97204,330,330,0,10/13/2020 16:20,2021-04-21 10:54:00,Alabama
2,4,4/16/1990,Winston-Salem,NC,27106,10790,14290,3500,8/18/2020 13:21,2022-06-30 22:22:00,North Carolina
3,5,3/24/1994,Winston-Salem,NC,27109,650,650,0,8/21/2020 11:27,2020-12-30 10:57:00,North Carolina
4,6,10/9/1995,G,AL,85588,7085,7395,310,8/18/2020 14:28,2022-06-08 23:55:00,Alabama